### ISSUE TITLE
Support ioredis

### ISSUE THREAD

**Issue by xavierchow** [strongloop/loopback-connector-redis#17]
The [ioredis](https://github.com/luin/ioredis) is more full featured redis client with support of cluster, sentinel, etc. Is there any plan to support ioredis as the underlying redis client?

**Comment by superkhau** [comment]
There are no plans in the works yet, but `ioredis` looks interesting. I'll bring it up during our roadmap discussions. Closing this issue as there is nothing ot resolve here.
