### ISSUE TITLE
"TypeError: Cannot read property 'package' of undefined" while adding datasource

### ISSUE THREAD

**Issue by Allan1** [strongloop/loopback-connector-redis#19]
Hi there,

I'm new to LoopbackJS but already a fan, and I'm trying to use Redis as a datasource.
I successfully installed Redis and loopback-connector-redis, however when I try to add it as a datasource (slc loopback:datasource) I run into the following error:

? Enter the data-source name: redisDB
? Select the connector for redis: other
? Enter the connector name without the loopback-connector- prefix: redis
events.js:154
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'package' of undefined
    at module.exports.yeoman.generators.Base.extend.installConnector (/usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/datasource/index.js:202:24)
    at /usr/local/lib/node_modules/strongloop/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Am I missing something?

**Comment by marysgonzalez** [comment]
It is happening to me too, using loopback-component-push as the instructions says.

**Comment by superkhau** [comment]
Weird, sounds like a bug, have you guys tried manually installing it via `npm install loopback-connector-redis`?

**Comment by superkhau** [comment]
I just tested it locally and it somewhat works now. You need to go through the same steps as above, but when asked for a datasource name:

```
? Enter the connector name without the loopback-connector- prefix:
```

Entering `loopback-connector-redis` (with the `loopback-connector` prefix) and it will install properly.

Created a follow up issue at https://github.com/strongloop/generator-loopback/issues/231.

Closing this issue as resolved.
